Fix for incremental run and snowflake error
fivetran/dbt_amplitude pull request #9
Opened 2023-01-18 18:03 UTC by fivetran-reneeli

**Are you a current Fivetran customer?** 

internal
**What change(s) does this PR introduce?** 

- Removes the table materialization config in the dbt_project.yml which overrode the incremental config within model
- Adds additional dbt run in the integration testing to correctly test for incremental logic
- fix snowflake error for `Subquery containing correlated aggregate function [MAX(TRUNCTIMESTAMPTODay(STG_AMPLITUDE__EVENT.EVENT_TIME))] can only appear in having or select clause`
**Did you update the CHANGELOG?** 

- [x] Yes

**Does this PR introduce a breaking change?**

- [x] Yes (please provide breaking change details below.)
changing model materialization
- [ ] No  (please provide an explanation as to how the change is non-breaking below.)

**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)** 

- [x] Yes

**Is this PR in response to a previously created Bug or Feature Request**

- [x] Yes, Issue https://github.com/fivetran/dbt_amplitude/issues/8
- [ ] No 

**How did you test the PR changes?** 

 

- [x] Buildkite  
- [ ] Local (please provide additional testing details below)

**Select which warehouse(s) were used to test the PR**
 

- [x] BigQuery
- [x] Redshift
- [x] Snowflake
- [x] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
:dancer:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

2023-02-02 22:16 UTC, fivetran-reneeli commented
- [ ] reminder to change package deps

2023-02-06 21:25 UTC, fivetran-joemarkiewicz requested changes
@fivetran-reneeli thanks for working through these changes and getting the incremental logic to function properly! 

In addition to my comments below, I had another request to update the package code that wasn't touched in your latest updates. Essentially, when validating your changes I noticed it seemed like we were removing events that were not duplicate, but were in fact true events that were erroneously removed within the [amplitude__event_enhanced](https://github.com/fivetran/dbt_amplitude/blob/15d9099d82c6f83281248789274f27623e21ab6b/models/amplitude__event_enhanced.sql#L23-L38) and [amplitude__sessions](https://github.com/fivetran/dbt_amplitude/blob/15d9099d82c6f83281248789274f27623e21ab6b/models/amplitude__sessions.sql#L23-L39) models.

I found the trouble code to be the coalesce logic. This logic in each model is attempting to either use the record number from the `_insert_id` or the partition of the `event_id`, `device_id`, `client_event_time`, and `amplitude_user_id` fields. However, even if the `_insert_id` is null, the row_number record will still populate. Therefore, the coalesce will not function as intended and just always use the first check. This resulted in our logic deduping events that should not have been grouped together.

My proposal is to swap the logic from a coalesce, to instead be a case when on the assumption of the `_insert_id` not being null. For example, I was able to add this logic to both models and see the erroneous event deduplication issue to be resolved.
```sql
-- deduplicate
event_data as (
    
    select * 
    from (
        select 
            *,
            ---- proposed update below
            case when _insert_id is not null
                then row_number() over (partition by _insert_id order by client_upload_time desc)
                else row_number() over (partition by event_id, device_id, client_event_time, amplitude_user_id order by client_upload_time desc)
            end as nth_event_record
            ---- current logic commented out below
            -- coalesce(
            --     row_number() over (partition by _insert_id order by client_upload_time desc), 
            --     row_number() over (partition by event_id, device_id, client_event_time, amplitude_user_id order by client_upload_time desc)
            -- ) as nth_event_record

            from event_data_raw
        ) as duplicates
    where nth_event_record = 1
),
```

Let me know your thoughts on the above. If this is something we are going to update, let's be sure to add this to make the update and include section around this update in the CHANGELOG.

2023-02-06 22:17 UTC, fivetran-reneeli commented
- [ ] regen docs

2023-02-06 22:30 UTC, fivetran-reneeli commented on CHANGELOG.md
> +- Add an additional dbt run to our integration testing so that we're not just running on fresh data, and so that the second run uses the same data and runs with the incremental strategy.
that's true, this won't affect the customer. updated

2023-02-06 22:34 UTC, fivetran-reneeli commented on CHANGELOG.md
> +- Move the recursive subquery in the incremental logic in `int_amplitude__date_spine`, `amplitude__daily_performance`, `amplitude__event_enhanced`, `amplitude__sessions` into its own CTE to address w
Reworded, let me know what you think!

2023-02-06 22:35 UTC, fivetran-reneeli commented on models/amplitude__daily_performance.sql
> +    max_date as (
updated

2023-02-06 22:35 UTC, fivetran-reneeli commented on models/amplitude__daily_performance.sql
> +    ),
updated

2023-02-06 22:42 UTC, fivetran-reneeli commented on README.md
> +    date_range_start: '2022-01-01' # your start date here
moved to its own step and added the recommendation

2023-02-06 23:01 UTC, fivetran-reneeli commented on models/amplitude__daily_performance.sql
> +    ),
done

2023-02-06 23:01 UTC, fivetran-reneeli commented on models/amplitude__daily_performance.sql
> +        , max_date
Yeah it's an implicit cross-join so max_event_day will get joined to each record, yep!

2023-02-06 23:02 UTC, fivetran-reneeli commented on models/intermediate/int_amplitude__date_spine.sql
> +        where date_day >= max_date.max_event_day
As discussed we'll leave this as is since it acts as a buffer

2023-02-06 23:05 UTC, fivetran-reneeli commented on models/amplitude__daily_performance.sql
>      select *
Oh I see, you're adding an alias so that when select * occurs, we won't be bringing in `max_date` as well since it won't exist on the first run, since the incremental block wouldn't have been run yet. That makes sense

2023-02-07 20:21 UTC, fivetran-joemarkiewicz commented on README.md
> +## Step 4: Change event date range
Small terminology suggested change.
```suggestion
## Step 4: Configure event date range
```

2023-02-07 20:21 UTC, fivetran-joemarkiewicz commented on models/amplitude__daily_performance.sql
>      select *
Exactly! Thanks for updating.

2023-02-08 16:04 UTC, fivetran-joemarkiewicz approved these changes
@fivetran-reneeli I have a few comments, but should be easy enough to adjust before moving forward. As such, I will approve this PR. Thanks for working on these updates to the package! Let me know if you have any questions before moving forward with my suggestions.

2023-02-08 16:04 UTC, fivetran-joemarkiewicz commented on README.md
> +The default date range starts at '2020-01-01' and ends one month past the current day. To customize the date range, add the following configurations to your root `dbt_project.yml` file:
I think there is value in having the date ranges differ for these two use cases. Let's just highlight this in the documentation. Below is my suggested wording.

```suggestion
The default date range for the [stg_amplitude__event](https://github.com/fivetran/dbt_amplitude_source/blob/main/models/stg_amplitude__event.sql) model starts at '2020-01-01' and ends one month past the current day. Conversely, for the [date spine](https://github.com/fivetran/dbt_amplitude/blob/main/models/intermediate/int_amplitude__date_spine.sql) model in this package the default date range starts at `2020-01-01` and ends one day after the current day. To customize the date range, add the following configurations to your root `dbt_project.yml` file:
```

2023-02-08 16:04 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_amplitude__date_spine.sql
> +    select  {{ dbt.dateadd("month", 1, dbt.date_trunc("day", dbt.current_timestamp_backcompat())) }}
I don't feel the need to make the calendar a month in the future. A day for the calendar will suffice.
```suggestion
    -- select one day past current day
    select  {{ dbt.dateadd("day", 1, dbt.date_trunc("day", dbt.current_timestamp_backcompat())) }}
```

2023-02-08 16:04 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_amplitude__date_spine.sql
> +        where date_day >= max_date.max_event_day
There isn't a need to create a buffer for the date spine (since the days won't change day over day). We should keep the same condition as before here. Otherwise, we may accidentally bring in duplicate days during incremental runs.
```suggestion
        where date_day > max_date.max_event_day
```

2023-02-08 16:04 UTC, fivetran-joemarkiewicz commented on packages.yml
> +  warn-unpinned: false
Reminder to switch
```suggestion
 - package: fivetran/amplitude_source
   version: [">=0.3.0", "<0.4.0"]
```

2023-02-08 16:49 UTC, fivetran-reneeli commented on CHANGELOG.md
> +- Update the date spine (`int_amplitude__date_spine`) to have the last date be one month past the current day to act as a buffer.
Ahh I see, since the dates in the date spine we're controlling/creating, as opposed to in the event model

2023-02-08 16:51 UTC, fivetran-reneeli commented on README.md
> +The default date range starts at '2020-01-01' and ends one month past the current day. To customize the date range, add the following configurations to your root `dbt_project.yml` file:
Makes sense, merged this

2023-02-08 16:51 UTC, fivetran-reneeli commented on models/intermediate/int_amplitude__date_spine.sql
> +    select  {{ dbt.dateadd("month", 1, dbt.date_trunc("day", dbt.current_timestamp_backcompat())) }}
updated this

2023-02-08 21:48 UTC, merged